### ISSUE TITLE
[BUG] (Player isn't/is connected to proxy) is reversed (do again)

### ISSUE THREAD

**Issue by Lennord** [crewpvp/skcrew#11]
Good evening, the syntax problem has returned, it's always reversed

Syntaxe: `if player isn't/is connected to proxy`

Code:
```
on join:
	if player is connected to proxy:
		broadcast "yes connection player"
```

**Comment by Lotzyprod** [comment]
What proxy you use? Bungeecord or Velocity?
I didn't reproduce this bug on Velocity

**Comment by Lennord** [comment]
> What proxy do you use? Bungeecord or Velocity? I didn't reproduce this bug on Velocity

Use Waterfall-latest (1.20.1 Minecraft)

**Comment by Lotzyprod** [comment]
Ok, I saw what the problem is, you use 'on join', when you first enter the server (not switching between servers) the player is not yet considered as a 'proxy', since the player's connection packet has not yet had time to enter

**Comment by Lennord** [comment]
> Ok, I saw what the problem is, you use 'on join', when you first enter the server (not switching between servers) the player is not yet considered online on a 'proxy', since the player's connection packet has not yet had time to enter

ah ok, so what do I use?

**Comment by Lotzyprod** [comment]
What do you want to do?

**Comment by Lennord** [comment]
> What do you want to do?

in fact, I would like when a player connects to a server and it detects that he is connected to the proxy.

**Comment by Lotzyprod** [comment]
> > What do you want to do?
> 
> in fact, I would like when a player connects to a server and it detects that he is connected to the proxy.

When player connects to server he is already connected to proxy, but if you wanna handle any proxy connections you can use:
```
on player (join|connect)[(ed|s)] [to] proxy [server]:
```
for handle any proxy connections, or
```
player (join|connect)[(ed|s)] [to] (proxied|network) server
```
```
player (join|connect)[(ed|s)] [to] (proxied|network) server %string%
```
to handle connections to proxied servers

**Comment by Lennord** [comment]
> > > What do you want to do?
> > 
> > 
> > in fact, I would like when a player connects to a server and it detects that he is connected to the proxy.
> 
> When player connects to server he is already connected to proxy, but if you wanna handle any proxy connections you can use:
> 
> ```
> on player (join|connect)[(ed|s)] [to] proxy [server]:
> ```
> 
> for handle any proxy connections, or
> 
> ```
> player (join|connect)[(ed|s)] [to] (proxied|network) server
> ```
> 
> ```
> player (join|connect)[(ed|s)] [to] (proxied|network) server %string%
> ```
> 
> to handle connections to proxied servers

ok thank you very much, I will close this issue which is no longer a problem, thank you.
