### ISSUE TITLE
skcrew skript bug (honestly no idea how to name the title)

### ISSUE THREAD

**Issue by Misjudgments** [crewpvp/skcrew#17]
my server crashed a few times and since the only error i get is related to skcrew i thought i should come here and supply the errors and see if you can help me with it.
my skript version is 2.7.3, server version is paper 1.17.1.
would appreciate if you could help me figure it out.
this is the error log:
> [17:19:22] [Server thread/ERROR]: #!#! 
> [17:19:22] [Server thread/ERROR]: #!#! [Skript] Severe Error:
> [17:19:22] [Server thread/ERROR]: #!#! class com.lotzy.skcrew.spigot.gui.types.TypeGUI generated an exception while loading
> [17:19:22] [Server thread/ERROR]: #!#! 
> [17:19:22] [Server thread/ERROR]: #!#! Something went horribly wrong with Skript.
> [17:19:22] [Server thread/ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
> [17:19:22] [Server thread/ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
> [17:19:22] [Server thread/ERROR]: #!#! Following plugins are probably related to this error in some way:
> [17:19:22] [Server thread/ERROR]: #!#! Skcrew (https://github.com/crewpvp/skcrew) 
> [17:19:22] [Server thread/ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
> [17:19:22] [Server thread/ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
> [17:19:22] [Server thread/ERROR]: #!#! In that case, you will be given instruction on how should you report it.
> [17:19:22] [Server thread/ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
> [17:19:22] [Server thread/ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
> [17:19:22] [Server thread/ERROR]: #!#! 
> [17:19:22] [Server thread/ERROR]: #!#! Stack trace:
> [17:19:22] [Server thread/ERROR]: #!#! java.lang.IllegalArgumentException: Can't register com.lotzy.skcrew.spigot.gui.GUI with the code name guiinventory because that name is already used by gui inventory
> [17:19:22] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.registrations.Classes.registerClass(Classes.java:94)
> [17:19:22] [Server thread/ERROR]: #!#!     at Skcrew.jar//com.lotzy.skcrew.spigot.gui.types.TypeGUI.<clinit>(TypeGUI.java:15)
> [17:19:22] [Server thread/ERROR]: #!#!     at java.base/java.lang.Class.forName0(Native Method)
> [17:19:22] [Server thread/ERROR]: #!#!     at java.base/java.lang.Class.forName(Class.java:467)
> [17:19:22] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.util.Utils.getClasses(Utils.java:201)
> [17:19:22] [Server thread/ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:82)
> [17:19:22] [Server thread/ERROR]: #!#!     at Skcrew.jar//com.lotzy.skcrew.spigot.Config.loadGUIModule(Config.java:195)
> [17:19:22] [Server thread/ERROR]: #!#!     at Skcrew.jar//com.lotzy.skcrew.spigot.Skcrew.onEnable(Skcrew.java:38)
> [17:19:22] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
> [17:19:22] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
> [17:19:22] [Server thread/ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
> [17:19:22] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
> [17:19:22] [Server thread/ERROR]: #!#!     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
> [17:19:22] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733)
> [17:19:22] [Server thread/ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:317)
> [17:19:22] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1220)
> [17:19:22] [Server thread/ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
> [17:19:22] [Server thread/ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:833)
> [17:19:22] [Server thread/ERROR]: #!#! 
> [17:19:22] [Server thread/ERROR]: #!#! Version Information:
> [17:19:22] [Server thread/ERROR]: #!#!   Skript: 2.7.3
> [17:19:22] [Server thread/ERROR]: #!#!     Flavor: skriptlang-github
> [17:19:22] [Server thread/ERROR]: #!#!     Date: 15:29:36.833117400
> [17:19:22] [Server thread/ERROR]: #!#!   Bukkit: 1.17.1-R0.1-SNAPSHOT
> [17:19:22] [Server thread/ERROR]: #!#!   Minecraft: 1.17.1
> [17:19:22] [Server thread/ERROR]: #!#!   Java: 17.0.7 (OpenJDK 64-Bit Server VM 17.0.7+7)
> [17:19:22] [Server thread/ERROR]: #!#!   OS: Linux amd64 6.2.0-39-generic
> [17:19:22] [Server thread/ERROR]: #!#! 
> [17:19:22] [Server thread/ERROR]: #!#! Server platform: Paper
> [17:19:22] [Server thread/ERROR]: #!#! 
> [17:19:22] [Server thread/ERROR]: #!#! Current node: null
> [17:19:22] [Server thread/ERROR]: #!#! Current item: null
> [17:19:22] [Server thread/ERROR]: #!#! 
> [17:19:22] [Server thread/ERROR]: #!#! Thread: Server thread
> [17:19:22] [Server thread/ERROR]: #!#! 
> [17:19:22] [Server thread/ERROR]: #!#! Language: english
> [17:19:22] [Server thread/ERROR]: #!#! Link parse mode: DISABLED
> [17:19:22] [Server thread/ERROR]: #!#! 
> [17:19:22] [Server thread/ERROR]: #!#! End of Error.
> [17:19:22] [Server thread/ERROR]: #!#!

**Comment by Lotzyprod** [comment]
Just disable gui module if you also use skript-gui addon
