### ISSUE TITLE
Bedrock Form Open with ID

### ISSUE THREAD

**Issue by jugandomiguel** [crewpvp/skcrew#5]
create modal form named "Shop" with id "shop_buy":
open shop_buy to {_p}

Im trying to open the shop with id but is not working

**Comment by Lotzyprod** [comment]
Sorry for late anwser, we work at addon at now, updates coming soon

**Comment by jugandomiguel** [comment]
haha, dw you answered me in discord anyway ty for the response

**Comment by Lotzyprod** [comment]
global forms completely removed due to this is not really a Skript style feature, just store form inside variable

**Comment by jugandomiguel** [comment]
oke, but now's fixed?

**Comment by Lotzyprod** [comment]
yea, but now global ids removed, just save form in global variable , like after creating form:
set {someVar} to last created form
Documentation at rewrite stage, just use skunity docs
