### ISSUE TITLE
[BUG] (Player isn't/is connected to proxy) is reversed

### ISSUE THREAD

**Issue by Lennord** [crewpvp/skcrew#8]
Good evening,

I use version 3.1 of skCrew and there is an inverse following the syntax `if player isn't/is connected to proxy`, in fact the "is" is equal to "isn't" and "isn't" is equal to "is", is that possible to correct the problem?

**Comment by Lotzyprod** [comment]
Looking through this right now, it's far from just an inverted condition :)

**Comment by Lotzyprod** [comment]
Fixed

**Comment by Lennord** [comment]
![Capture](https://github.com/crewpvp/skcrew/assets/65398078/2a7d9fcf-2f08-4a13-afcb-6691e144f2d6)

I have this error

**Comment by Lennord** [comment]
> Fixed

![Capture](https://github.com/crewpvp/skcrew/assets/65398078/8832ced4-a749-48ab-822b-a25ddc7406aa)

I have an error and the syntax does not work.

Error:
```
on join:
	if player is connected to proxy:
		broadcast "yes connection player"
```

**Comment by Lennord** [comment]
> > Fixed
> 
> ![Capture](https://private-user-images.githubusercontent.com/65398078/298238914-8832ced4-a749-48ab-822b-a25ddc7406aa.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NDUyMDQsIm5iZiI6MTcwNTc0NDkwNCwicGF0aCI6Ii82NTM5ODA3OC8yOTgyMzg5MTQtODgzMmNlZDQtYTc0OS00OGFiLTgyMmItYTI1ZGRjNzQwNmFhLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDEwMDE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkZjEwMzhlNjllNzEwN2E3Yzc5YzMxNjYzZTQxY2JlMTQyMGYxZjE2ZTNiNTNlZDE2N2NjOGNmNDUwNmI5NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ohtjcoy5UMgfuZEwnHTvqb2-Rog3tAON_mA1LvDGxLo)
> 
> I have an error and the syntax does not work.
> 
> Code:
> 
> ```
> on join:
> 	if player is connected to proxy:
> 		broadcast "yes connection player"
> ```

Hello, it's okay, it's been corrected since the last update. Thanks !
